language: julia
julia:
- 1.0
- 1.1
- 1.2
- nightly
matrix:
  allow_failures:
    - julia: nightly
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
notifications:
  on_success: never 
  on_failure: change